apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/part-of: acme-support
    includeSelectors: false
resources:
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - backend-pdb.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-pdb.yaml
  - ingress.yaml
  - retention-cronjob.yaml
  - networkpolicy.yaml
images:
  - name: acme-backend
    newName: ghcr.io/likhithv02/customer-support-agent-backend
    newTag: latest
  - name: acme-frontend
    newName: ghcr.io/likhithv02/customer-support-agent-frontend
    newTag: latest
